name: Auto build (imgui)
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 0,3'
  push:
    paths:
      - 'scripts/imgui.onion'
jobs:
  build_imgui:
    uses: ./.github/workflows/action_lib.yml
    secrets: inherit
    with:
      lib: imgui
