name: Auto build (freeimage)
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 0,3'
  push:
    paths:
      - 'scripts/freeimage.onion'
jobs:
  build_freeimage:
    uses: ./.github/workflows/action_lib.yml
    secrets: inherit
    with:
      lib: freeimage
