name: Auto build (mbedtls)
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 0,3'
  push:
    paths:
      - 'scripts/mbedtls.onion'
jobs:
  build_mbedtls:
    uses: ./.github/workflows/action_lib.yml
    secrets: inherit
    with:
      lib: mbedtls
