name: Auto build (freetype)
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 0,3'
  push:
    paths:
      - 'scripts/freetype.onion'
jobs:
  build_freetype:
    uses: ./.github/workflows/action_lib.yml
    secrets: inherit
    with:
      lib: freetype
