name: Auto build (lua)
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 0,3'
  push:
    paths:
      - 'scripts/lua.onion'
jobs:
  build_lua:
    uses: ./.github/workflows/action_lib.yml
    secrets: inherit
    with:
      lib: lua
