name: Auto build (gtest)
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 0,3'
  push:
    paths:
      - 'scripts/gtest.onion'
jobs:
  build_gtest:
    uses: ./.github/workflows/action_lib.yml
    secrets: inherit
    with:
      lib: gtest
