name: Auto build (zlib)
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 0,3'
  push:
    paths:
      - 'scripts/zlib.onion'
jobs:
  build_zlib:
    uses: ./.github/workflows/action_lib.yml
    secrets: inherit
    with:
      lib: zlib
