name: Auto build (curl)
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 0,3'
  push:
    paths:
      - 'scripts/curl.onion'
jobs:
  build_curl:
    uses: ./.github/workflows/action_lib.yml
    secrets: inherit
    with:
      lib: curl
