name: Auto build (dxc)
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 0,3'
  push:
    paths:
      - 'scripts/dxc.onion'
jobs:
  build_dxc:
    uses: ./.github/workflows/action_lib.yml
    secrets: inherit
    with:
      lib: dxc
