name: Auto build (recast)
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 0,3'
  push:
    paths:
      - 'scripts/recast.onion'
jobs:
  build_recast:
    uses: ./.github/workflows/action_lib.yml
    secrets: inherit
    with:
      lib: recast
