name: Auto build (bullet)
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 0,3'
  push:
    paths:
      - 'scripts/bullet.onion'
jobs:
  build_bullet:
    uses: ./.github/workflows/action_lib.yml
    secrets: inherit
    with:
      lib: bullet
