name: Auto build (openal)
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 0,3'
  push:
    paths:
      - 'scripts/openal.onion'
jobs:
  build_openal:
    uses: ./.github/workflows/action_lib.yml
    secrets: inherit
    with:
      lib: openal
